version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000 &&
             python manage.py filldata_command"
    volumes:
      - ./vristo-django:/app
    ports:
      - "8000:8000"
    env_file:
      - ./vristo-django/.env
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_PASSWORD: dashboard
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A vristo worker -l info --pool=solo -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./vristo-django:/app
    env_file:
       - ./vristo-django/.env
    depends_on:
      - db
      - redis

  flower:
    build: ./
    command: celery -A vristo flower
    volumes:
       - ./vristo-django:/app
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - celery
      - redis

  bot:
    build: .
    command: python main/bot2.py
    volumes:
        - ./vristo-django:/app
    env_file:
      - ./vristo-django/.env
    depends_on:
      - django


volumes:
  postgres_data:

#     celery -A vristo  worker -l info --pool=solo
#  celery -A vristo flower
#  celery -A vristo beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#   celery -A vristo inspect registered