# Generated by Django 4.2.7 on 2023-11-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cdn_note_domain_note_hosting_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='note',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
