# Generated by Django 4.2.7 on 2023-12-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_website_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='domain_hash',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
