# Generated by Django 4.2.7 on 2024-01-10 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_website_check_enabled_website_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=3)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.website')),
            ],
        ),
    ]
