# Generated by Django 4.2.7 on 2024-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_unavailablelog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailablelog',
            name='status',
        ),
        migrations.AddField(
            model_name='unavailablelog',
            name='end_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unavailablelog',
            name='start_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
